from report_api.Report import Report
book_names = {

    "ФиксиКнижки - Солнечная батарея": "fixies",
    "ФиксиКнижки - Лифт": "fixies",
    "Фиксики МиниИгры - Холодильник": "fixies",
    "Фиксики МиниИгры - Стиральная Машина": "fixies",
    "Фиксики МиниИгры - Лифт": "fixies",
    "ФиксиКнижки - Холодильник": "fixies",
    "ФиксиКнижки - Стиральная Машина": "fixies",
    "Фиксики МиниИгры - Солнечная батарея": "fixies",
    "ФиксиКнижки - Компас": "fixies",
    "ФиксиКнижки - Рефлексы": "fixies",
    "The Fixies Books The Elevator": "fixies",
    "The Fixies Books The Refrigerator": "fixies",
    "The Fixies Books The Washing Machine": "fixies",
    "ФиксиКнижки - Короткое Замыкание": "fixies",
    "Фиксики МиниИгры - Компас": "fixies",
    "Фиксики МиниИгры - Рефлексы": "fixies",
    "Фиксики МиниИгры - Короткое Замыкание": "fixies",
    "The Fixies Games 1": "fixies",
    "The Fixies Games 2": "fixies",
    "The Fixies Games 3": "fixies",
    "ФиксиКнижки - Фонарик": "fixies",
    "Фиксики МиниИгры - Фонарик": "fixies",
    "ФиксиКнижки - Степлер": "fixies",
    "Фиксики МиниИгры - Степлер": "fixies",
    "ФиксиКнижки - Сотовый Телефон": "fixies",
    "Фиксики МиниИгры - Сотовый Телефон": "fixies",
    "The Fixies Books - The Cell Phone": "fixies",
    "The Fixies Games 10": "fixies",
    "The Fixies Books - The Solar Battery": "fixies",
    "Fixiki Games 10": "fixies",
    #  "":"fixies",
    # "":"fixies",
    #  "":"fixies",


    "МимиМишки Игры 9": "mishki",
    "МимиМишки Игры 2": "mishki",
    "МимиМишки Игры 3": "mishki",
    "МимиМишки - Борьба за урожай": "mishki",
    "МимиМишки - Как лечить деревья": "mishki",
    "МимиМишки - Несовременная еда": "mishki",
    "МимиМишки Игры 4": "mishki",
    "МимиМишки Игры 6": "mishki",
    "МимиМишки - Лучшая Напоминалка": "mishki",
    "МимиМишки - Грибы и Листья": "mishki",
    "МимиМишки - Путешествие": "mishki",
    "МимиМишки Игры 8": "mishki",
    "МимиМишки Игры 1": "mishki",
    "МимиМишки Игры 7": "mishki",
    "МимиМишки - Домовой": "mishki",
    "МимиМишки - Звёздное небо": "mishki",
    "МимиМишки - Фотоохота": "mishki",
    "МимиМишки Игры 5": "mishki",
    "МимиМишки - Лучшая напоминалка": "mishki",
    "Мимимишки Звёздное небо": "mishki",
    "МимиМишки - Бессонница": "mishki",
    "Bebebears Star Story": "mishki",
    "Bebebears Mushroom Machine Mayhem": "mishki",
    "Bebebears A Journey": "mishki",
    "Bebebears Wildlife Photography": "mishki",
    "МимиМишки - Глобальное потепление": "mishki",
    "Bebebears Mimigames 1": "mishki",
    "МимиМишки Игры 10": "mishki",
    "МимиМишки Игры 11": "mishki",
    "Bebebears Mimigames 2": "mishki",
    "Bebebears Mimigames 3": "mishki",
    "Bebebears Mimigames 4": "mishki",
    "МимиМишки - Огородники": "mishki",
    "МимиМишки Игры 12": "mishki",
    "МимиМишки - Медовая История": "mishki",
    "МимиМишки Игры 13": "mishki",
    # "":"mishki",
    # "":"mishki",
    # "":"mishki",
    # "":"mishki",
    # "":"mishki",
    # "":"mishki",
    # "":"mishki",
    # "":"mishki",
    # "":"mishki",
    # "":"mishki",
    # "":"mishki",
    # "":"mishki",
    # "":"mishki",





    "Машкины Страшилки - Про жучка": "spookystories",
    "Машкины Страшилки Игры 2": "spookystories",
    "Машкины Страшилки Игры 1": "spookystories",
    "Машкины Страшилки - Про мальчика": "spookystories",
    "Машкины Страшилки Игры 3": "spookystories",
    "Машкины Страшилки - Про монстров": "spookystories",
    "Машкины Страшилки - О котёнке": "spookystories",
    "Masha's Spooky Stories About Bug": "spookystories",
    "Masha's Spooky Stories About Boy": "spookystories",
    "Masha's Spooky Stories About Monsters": "spookystories",
    "Машкины Страшилки - О Новогодних Стишках": "spookystories",
    "Машкины Страшилки Игры 4": "spookystories",
    "Masha's Spooky Stories Games 2": "spookystories",
    "Masha's Spooky Stories Games 1": "spookystories",
    "Masha's Spooky Stories Games 3": "spookystories",
    "Машкины Страшилки Игры 5": "spookystories",
    "Машкины Страшилки Игры 6": "spookystories",
    "Машкины Страшилки - Про Суеверную Девочку": "spookystories",
    "Masha's Spooky Stories Games 6": "spookystories",
    "Masha's Spooky Stories About Superstitious Girl": "spookystories",
    # "":"spookystories",
    # "":"spookystories",
    # "":"spookystories",
    # "":"spookystories",


    "Симби и Орёл": "tales",
    "Interactive Alphabet": "tales",
    "Красная Шапочка": "tales",
    "Pussy Cat in Boots": "tales",
    "Притчи Мехди": "tales",
    "Снежная Королева (первая часть)": "tales",
    "The Little Red Hen": "tales",
    "Cinderella in the Twilight Zone": "tales",
    "Симби и Люми": "tales",
    "Рыжая Курочка": "tales",
    "Зомбушка": "tales",
    "Белоснежка": "tales",
    "Румпельштильцхен": "tales",
    "Интерактивный Алфавит": "tales",
    "Красавица и Чудовише": "tales",
    "Чудилёныш - Розовое Волшебство": "tales",
    "Кошка в Сапожках": "tales",
    "Гадкий Утенок": "tales",
    "Beauty and Beast": "tales",
    "Rumpelstiltskin": "tales",
    "Гадкий Утёнок": "tales",
    "Снежная Королева (вторая часть)": "tales",

    "Ам Ням Рождественский Выпуск": "omnom",
    "Ам Ням Мини-Игры 1": "omnom",
    "Ам Ням Вокруг Света Ярмарка": "omnom",
    "Ам Ням Мини-Игры 2": "omnom",
    "Om Nom Stories Christmas Story": "omnom",
    "Om Nom Stories Games 1": "omnom",
    "Om Nom Stories The Fair": "omnom",
    # "":"omnom",
    # "":"omnom",
    # "":"omnom",

    "Три Кота Варенье": "trikota",
    "Три Кота Игры Варенье": "trikota",
    "Три Кота Велосипед": "trikota",
    "Три Кота Музыкальная Открытка": "trikota",
    "Три Кота Игры Музыкальная Открытка": "trikota",
    "Три Кота Киношедевр": "trikota",
    "Три Кота Игры Киношедевр": "trikota",
    "Три Кота Игры Велосипед": "trikota",
    # "":"trikota",
    # "":"trikota",
    # "":"trikota",
    # "":"trikota",

}




free_books = {"mishki": {"rus": {"МимиМишки - Звёздное небо", "МимиМишки Игры 1"},
                         "eng": {"Bebebears Star Story", "Bebebears Games 1"}},
              "fixies": {"rus": {"ФиксиКнижки - Сотовый Телефон", "Фиксики МиниИгры - Сотовый Телефон"},
                         "eng": {"The Fixies Books - The Cell Phone", "The Fixies Games 1"}},
              "spookystories": {"rus": {"Машкины Страшилки - Про Суеверную Девочку", "Машкины Страшилки Игры 6"},
                                "eng": {
                                    "Masha's Spooky Stories About Superstitious Girl",
                                    "Masha's Spooky Stories Games 6"}},
               "trikota": {"rus": {"Три Кота Варенье", "Три Кота Игры Варенье"}},
               "omnom": {"rus": {"Ам Ням Рождественский Выпуск", "Ам Ням Мини-Игры 1"},
                        "eng": {"Om Nom Stories Christmas Story", "Om Nom Stories Games 1"}},
               "tales": {"rus": {"Интерактивный Алфавит", "Снежная Королева (первая часть)"},
                        "eng": {"Interactive Alphabet", "Beauty and Beast"}}
               }

books = {"mishki": {"rus": {"МимиМишки - Звёздное небо", "МимиМишки Игры 1", "МимиМишки Игры 9",
                            "МимиМишки Игры 2",
                            "МимиМишки Игры 3",
                            "МимиМишки - Борьба за урожай",
                            "МимиМишки - Как лечить деревья",
                            "МимиМишки - Несовременная еда",
                            "МимиМишки Игры 4",
                            "МимиМишки Игры 6",
                            "МимиМишки - Лучшая Напоминалка",
                             "МимиМишки - Грибы и Листья",
                             "МимиМишки - Путешествие",
                             "МимиМишки Игры 8",
                             "МимиМишки Игры 1",
                             "МимиМишки Игры 7",
                             "МимиМишки - Домовой",
                             "МимиМишки - Звёздное небо",
                             "МимиМишки - Фотоохота",
                             "МимиМишки Игры 5",
                             "МимиМишки - Лучшая напоминалка",
                             "Мимимишки Звёздное небо",
                             "МимиМишки - Бессонница",
                             "МимиМишки - Глобальное потепление",
                             "МимиМишки Игры 10",
                             "МимиМишки Игры 11",
                             "МимиМишки - Огородники",
                             "МимиМишки Игры 12",
                             "МимиМишки - Медовая История",
                             "МимиМишки Игры 13"
                             },
                     "eng": {"Bebebears Star Story", "Bebebears Games 1", "Bebebears Star Story",
                            "Bebebears Mushroom Machine Mayhem",
                            "Bebebears A Journey",
                            "Bebebears Wildlife Photography",
                            "Bebebears Mimigames 1",
                            "Bebebears Mimigames 2",
                            "Bebebears Mimigames 3",
                            "Bebebears Mimigames 4",
                            "Bebebears Games 5",
                            "Bebebears Games 6",
                            "Bebebears Games 7",
                            "Bebebears Games 8",
                            "Bebebears Games 9",
                            "Bebebears Games 10",
                            "Bebebears Old-Fashioned Food",
                            "Bebebears The House Spirit",
                            "Bebebears How to Cure a Tree",
                            "Bebebears The Best Reminder",
                            "Bebebears Insomnia",
                            "Bebebears Harvest Hero"

                            }},
          "fixies": {"rus": {"ФиксиКнижки - Сотовый Телефон",
                            "Фиксики МиниИгры - Сотовый Телефон",
                            "ФиксиКнижки - Солнечная батарея",
                            "ФиксиКнижки - Лифт",
                            "Фиксики МиниИгры - Холодильник",
                            "Фиксики МиниИгры - Стиральная Машина",
                            "Фиксики МиниИгры - Лифт",
                            "ФиксиКнижки - Холодильник",
                            "ФиксиКнижки - Стиральная Машина",
                            "Фиксики МиниИгры - Солнечная батарея",
                            "ФиксиКнижки - Компас",
                            "ФиксиКнижки - Рефлексы",
                            "ФиксиКнижки - Короткое Замыкание",
                            "Фиксики МиниИгры - Компас",
                            "Фиксики МиниИгры - Рефлексы",
                            "Фиксики МиниИгры - Короткое Замыкание",
                            "ФиксиКнижки - Фонарик",
                            "Фиксики МиниИгры - Фонарик",
                            "ФиксиКнижки - Степлер",
                            "Фиксики МиниИгры - Степлер",
                            "ФиксиКнижки - Сотовый Телефон",
                            "Фиксики МиниИгры - Сотовый Телефон"},
                    "eng": {"The Fixies Books - The Cell Phone",
                            "The Fixies Games 1",
                            "The Fixies Books The Elevator",
                            "The Fixies Books The Refrigerator",
                            "The Fixies Books The Washing Machine",
                            "The Fixies Games 1",
                            "The Fixies Games 2",
                            "The Fixies Games 3",
                            "The Fixies Books - The Cell Phone",
                            "The Fixies Games 10",
                            "The Fixies Books - The Solar Battery",
                            "Fixiki Games 10"}},
          "spookystories": {"rus": {"Машкины Страшилки - Про Суеверную Девочку",
                                   "Машкины Страшилки Игры 1",
                                   "Машкины Страшилки - Про жучка",
                                   "Машкины Страшилки Игры 2",
                                   "Машкины Страшилки Игры 1",
                                   "Машкины Страшилки - Про мальчика",
                                   "Машкины Страшилки Игры 3",
                                   "Машкины Страшилки - Про монстров",
                                   "Машкины Страшилки - О котёнке",
                                   "Машкины Страшилки Игры 5",
                                   "Машкины Страшилки Игры 6",
                                   "Машкины Страшилки - Про Суеверную Девочку",
                                   "Машкины Страшилки - О Новогодних Стишках",
                                   "Машкины Страшилки Игры 4"},
                           "eng": {"Masha's Spooky Stories About Superstitious Girl",
                                   "Masha's Spooky Stories Games 1",
                                   "Masha's Spooky Stories About Bug",
                                   "Masha's Spooky Stories About Boy",
                                   "Masha's Spooky Stories About Monsters",
                                   "Masha's Spooky Stories Games 2",
                                   "Masha's Spooky Stories Games 1",
                                   "Masha's Spooky Stories Games 3",
                                   "Masha's Spooky Stories Games 6",
                                   "Masha's Spooky Stories About Superstitious Girl",
                                   "Masha's Spooky Stories About Kitten",
                                   "Masha's Spooky Stories Games 4"}},
          "trikota": {"rus": {"Три Кота Варенье",
                             "Три Кота Игры Варенье",
                             "Три Кота Варенье",
                             "Три Кота Игры Варенье",
                             "Три Кота Велосипед",
                             "Три Кота Музыкальная Открытка",
                             "Три Кота Игры Музыкальная Открытка",
                             "Три Кота Киношедевр",
                             "Три Кота Игры Киношедевр",
                             "Три Кота Игры Велосипед"},
                     "eng": set()},
          "omnom": {"rus": {"Ам Ням Рождественский Выпуск",
                           "Ам Ням Мини-Игры 1",
                           "Ам Ням Рождественский Выпуск",
                           "Ам Ням Мини-Игры 1",
                           "Ам Ням Вокруг Света Ярмарка",
                           "Ам Ням Мини-Игры 2",
                           "Приключения Ам Няма",
                           "Ам Ням Мини-Игры 3",
                           "Ам Ням Мини-Игры 4",
                           "Ам Ням Мини-Игры 6",
                           "Ам Ням Мини-Игры 5",
                           "Ам Ням Мини-Игры 7",
                           "Ам Ням Мини-Игры 8",
                           "Ам Ням Мини-Игры 09",
                           "Ам Ням Мини-Игры 10",
                           "Ам Ням Мини-Игры 11"},
                   "eng": {"Om Nom Stories Christmas Story",
                           "Om Nom Stories Games 1",
                           "Om Nom Stories",}},
          "tales": {"rus": {"Симби и Орёл",

                           "Гадкий Утёнок",
                           "Снежная Королева (вторая часть)",
                           "Красная Шапочка",
                           "Притчи Мехди",
                           "Снежная Королева (первая часть)",
                           "Симби и Люми",
                           "Рыжая Курочка",
                           "Зомбушка",
                           "Белоснежка",
                           "Румпельштильцхен",
                           "Интерактивный Алфавит",
                           "Красавица и Чудовише",
                           "Чудилёныш - Розовое Волшебство",
                           "Кошка в Сапожках",
                           "Гадкий Утенок"},
                   "eng": {"Beauty and Beast",
                           "Rumpelstiltskin",
                           "Interactive Alphabet",
                           "Pussy Cat in Boots",
                           "The Little Red Hen",
                           "Cinderella in the Twilight Zone"}}}
